version: "3.1"

services:
 app:
    build: docker/php
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php/php.ini-production:/usr/local/etc/php/php.ini
    tty: true
    stdin_open: true
    ports:
      - 9210:9210
      - 9200:9200

 db:
   image: mariadb
   restart: unless-stopped
   tty: true
   ports:
    - 3306:3306
   environment:
     MYSQL_DATABASE: "laravel"
     MYSQL_USER: "laravel"
     MYSQL_PASSWORD: "root"
     MYSQL_ROOT_PASSWORD: "root"
     SERVICE_TAGS: dev
     SERVICE_NAME: mysql
   volumes:
    - ./docker/mysql/data:/var/lib/mysql
    - ./docker/mysql/files:/var/lib/mysql-files/

 webserver:
   image: nginx:alpine
   working_dir: /application
   volumes:
    - .:/application
    - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
   ports:
    - 80:80

 cache:
   image: redis:alpine
   ports:
     - 6379:6379
   volumes:
     - 'laravel-redis:/data'
   healthcheck:
     test: [ "CMD", "redis-cli", "ping" ]

volumes:
  laravel-redis:
    driver: local